export default {
  GET_CONTACT_START: "contacts/GET_CONTACT-START",
  GET_CONTACT_SUCCESS: "contacts/GET_CONTACT_SUCCESS",
  GET_CONTACT_FAILURE: "contacts/GET_CONTACT_FAILURE",

  ADD_CONTACT_START: "contacts/ADD_CONTACT_START",
  ADD_CONTACT_SUCCESS: "contacts/ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "contacts/ADD_CONTACT_FAILURE",

  DELETE_CONTACT_START: "contacts/DELETE_CONTACT_START",
  DELETE_CONTACT_SUCCESS: "contacts/DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "contacts/DELETE_CONTACT_FAILURE",

  FILTER_CONTACT: "contacts/FILTER_CONTACT",
};
