export default {
  LOADING_START: "auth/LOADING_START",
  LOADING_END: "auth/LOADING_END",

  GET_USER_SUCCESS: "auth/GET_USER_SUCCESS",
  GET_USER_FAILURE: "auth/GET_USER_FAILURE",

  LOGIN_START: "auth/LOGIN_START",
  LOGIN_SUCCESS: "auth/LOGIN_SUCCESS",
  LOGIN_FAILURE: "auth/LOGIN_FAILURE",

  REGISTER_START: "auth/REGISTER_START",
  REGISTER_SUCCESS: "auth/REGISTER_SUCCESS",
  REGISTER_FAILURE: "auth/REGISTER_FAILURE",

  LOGOUT_START: "auth/LOGOUT_START",
  LOGOUT_SUCCESS: "auth/LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "auth/LOGOUT_FAILURE",
};
